### PR TITLE
Add configuration items and update how hosts are defined

### PR DESCRIPTION
**Pull request by jpiron**

### CODE REVIEW

**Comment by jpiron** [comment]
Hi !

Any feedback on this ?
I can split this up to several pull requests if you'd like.

**Comment by bertvv** [comment]
Sorry, I haven't been able to look at this earlier. I'm going to check it out. Thank you for this contribution!

**Comment by bertvv** [comment]
I'm going to test the changes and will release a new version with your contribution included. Thank you so much!

**Comment by jpiron** [comment]
Thank you !

**Pull request merged**
